admin_password: root
node:
  count: 1  # this number specifies the number of VMs that will be created
  cpus: 4
  memory: 8000
ip:
  node:   172.22.101.111  # starting IP address.
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
